apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-srv
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: "letsencrypt-prod"

spec:
  tls:
    - hosts:
      - capitalcoin.space
      secretName: awt-tls
  rules:
    - host: capitalcoin.space
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: social-service
                port:
                  number: 3003